Merged revisions 5310, 5311, 5313, 5322, 5323, 5327, 5329, 5337, 5338 from branches/gnucobol-3.x: ........ build system update
* configure.ac: require autoconf 2.70 and drop check for lex-library with noyywrap option for AC_PROG_LEX
* HACKING: document dependencies autoconf 2.70 and automake 1.16 and several smaller text updates
* Makefile.am (checkmanual-code-coverage, checkall-code-coverage): new targets removing the need to do that manually
* build_aux/ltmain.sh, m4/libtool.m4, m4/ltoptions.m4, m4/ltversion.m4

cobc:
* pplex.l, scanner.l: use noyywrap option instead of manually defining related code parts
........
updaste for NIST85

* DEPENDENCIES: added perl for running NIST85
* tests/cobol85:
	* summary.pl: compute total duration and modules executed, output those to stderr at the end; close file handles
	* Makefile.am (summary.out): new target depending on summary.log
	* Makefile.am (summary.log): catch stderr of summary.pl into summary.out  file and output that on stdout
	* Makefile.am (URL_NEWCOB_Z): replaced by web archive URL
........
minor doc changes
........
testsuite environment update

tests:
* atlocal.in (set_utf8_locale): new function for the testsuite enabling tests to either run with UTF8 locale or skip
* atlocal.in: use configure-setup for the grep binary
* atlocal_win: updated to current atlocal.in

[to be used for encoding and possibly screenio tests]
........
work on "make checkmanual"

README: add documentation for "make checkmanual"

tests/run_prog_manual.sh.in:
* adding testrunner tmux as alternative to screen
* allow to override the deduced test runner by environment variable TESTRUNNER
* new option to call with parameter "attach" and "kill" for either attaching to or killing test runner sessions in screen/tmux
* enhance portability and use abs_builddir
*  (_test_with_screen): use separate SCREENDIR to ensure using system defaults and work around WSL regressions
* (_test_with_cmd): work around cmd quoting by using a dynamically created sub command file
........
build system update

build_aux:
* ar-lib, config.guess, config.rpath, config.sub, texinfo.tex: updated to recent versions from https://git.savannah.gnu.org/cgit/gnulib.git/tree/build-aux/
configure: re-ordered gettext/conv checks
........
work on ALPHABET definitions, especially ALPHABET FOR NATIONAL - C90 fix for r5310

cobc/typeck.c (validate_alphabet): fixed
........
added missing iconv.m4 update - follow-up to r5310

* m4/iconv.m4: updated to current version from gnulib
........
work on ALPHABET definitions, especially ALPHABET FOR NATIONAL

cobc:	  
* typeck.c (validate_alphabet), tree.h (cb_alphabet_name): cater for national alphabets with increased size (max. 65535 instead of 255)
* typeck.c (validate_alphabet): check that alphabet and literal types match
* codegen.c (output_alphabet_name_definition): cater for national alphabet
* typeck.c (validate_alphabet): speedup for alphabet checks
* pplex.l (ppopen_get_file): explicit check for UTF16/UTF32 and hint to use iconv

additional, in preparation of character encoding support:
* configure.ac: new option --with-iconv
* DEPENDENCIES, NEWS: document usage of libiconv
........

diff --git a/tests/atlocal_win b/tests/atlocal_win
--- a/tests/atlocal_win
+++ b/tests/atlocal_win
@@ -5,7 +5,7 @@
 # a not POSIX build (OrangeC or Visual Studio build for example)
 # in a POSIX environment (like MinGW or Cygwin, possibly WSL).
 #
-# Copyright (C) 2003-2012, 2014-2023 Free Software Foundation, Inc.
+# Copyright (C) 2003-2012, 2014-2024 Free Software Foundation, Inc.
 # Written by Keisuke Nishida, Roger While, Simon Sobisch, Edward Hart
 #
 # This file is part of GnuCOBOL.
@@ -48,8 +48,8 @@ export LC_ALL
 unset LANG
 
 # define for performance checks (running code several thousand times)
-# comment manually if not needed
-COBOL_FLAGS="-DCHECK-PERF ${COBOL_FLAGS}"
+# uncomment manually if wanted, or set via environment
+# COBOL_FLAGS="-DCHECK-PERF ${COBOL_FLAGS}"
 
 FLAGS="-debug -Wall ${COBOL_FLAGS} -fdiagnostics-plain-output"
 # workaround to adjust the testsuite later:
@@ -90,11 +90,30 @@ _return_path () {
 		cygpath -pm "$1"
 	else
 		# check for WSL / Bash on Windows; ignore error messages (file not available)
-		if $(grep -q "Microsoft" /proc/sys/kernel/osrelease 2>/dev/null); then
+		if $($GREP -q "Microsoft" /proc/sys/kernel/osrelease 2>/dev/null); then
 			wslpath -w "$1"
 		else
 			echo "$1"
 		fi
+	fi
+}
+
+# as we run the testsuite in plain LC_ALL=C the system runs in a plain-as-possible environment;
+# in the case that we need UTF8 encoding within tests, we try to find out if a working UTF-8
+# locale is available, if not then we return with 77 which will skip the spßecific test needing it
+set_utf8_locale () {
+	# we need the locale binary to tell us how about the locales available
+	if [ -z "$(which locale)" ]; then
+		echo "Warning: no locale binary found."
+		exit 77  # return code for setting 
+	fi
+	unset LC_ALL
+	if [ -z "$LC_ALL" ]; then export LC_ALL=$(locale -a | $GREP -i -E "C\.utf.*8"     | head -n1); fi
+	if [ -z "$LC_ALL" ]; then export LC_ALL=$(locale -a | $GREP -i -E "en_US\.utf.*8" | head -n1); fi
+	if [ -z "$LC_ALL" ]; then export LC_ALL=$(locale -a | $GREP -i -E ".*\.utf.*8"    | head -n1); fi
+	if [ -z "$LC_ALL" ]; then
+		echo "Warning: no UTF-8 locale found."
+		exit 77
 	fi
 }
 
@@ -125,8 +144,8 @@ export COB_UNIX_LF
 COB_RUNTIME_CONFIG="$(_return_path "${abs_top_srcdir}/config/runtime_empty.cfg")"
 export COB_RUNTIME_CONFIG
 for cobenv in $(${LOCAL_ENV} ${COBCRUN} --runtime-conf \
-                 | grep " env:" | cut -d: -f2 | cut -d= -f1 \
-                 | grep -v "PATH" | grep -v "TERM"); \
+                 | $GREP " env:" | cut -d: -f2 | cut -d= -f1 \
+                 | $GREP -v "PATH" | $GREP -v "TERM"); \
 	do _unset_option $cobenv; \
 done
 
@@ -135,8 +154,8 @@ ${LOCAL_ENV} ${COBC} --verbose --info > info.out
 
 # ... and also unset for the compiler
 if test "$GNUCOBOL_TEST_LOCAL" != "1"; then
-	for cobenv in $(grep "env:" info.out | cut -d: -f2 | cut -d= -f1 \
-	              | grep -v "PATH"); \
+	for cobenv in $($GREP "env:" info.out | cut -d: -f2 | cut -d= -f1 \
+	              | $GREP -v "PATH"); \
 		do _unset_option $cobenv; \
 	done
 fi
@@ -150,20 +169,20 @@ export COB_MSG_FORMAT
 # different flags checked in the testsuite
 # note: kept intended to ease merge from atlocal.in
 
-	COB_OBJECT_EXT="$(grep COB_OBJECT_EXT info.out | cut -d: -f2 | cut -b2-)"
+	COB_OBJECT_EXT="$($GREP COB_OBJECT_EXT info.out | cut -d: -f2 | cut -b2-)"
 	COB_EXE_EXT=".exe"
 	COB_MODULE_EXT="dll"
 
-	if test $(grep -i -c "little-endian" info.out) = 0; then
+	if test $($GREP -i -c "little-endian" info.out) = 0; then
 		COB_BIGENDIAN="yes"
 	else
 		COB_BIGENDIAN="no"
 	fi
-	COB_HAS_64_BIT_POINTER=$(grep "64bit-mode" info.out | cut -d: -f2 | cut -b2-)
+	COB_HAS_64_BIT_POINTER=$($GREP "64bit-mode" info.out | cut -d: -f2 | cut -b2-)
 
-	cob_indexed=$(grep -i "indexed file" info.out | cut -d: -f2)
+	cob_indexed=$($GREP -i "indexed file" info.out | cut -d: -f2)
 	if test "x$cob_indexed" = "x"; then
-		cob_indexed=$(grep ISAM info.out | cut -d: -f2)
+		cob_indexed=$($GREP ISAM info.out | cut -d: -f2)
 	fi
 	case "$cob_indexed" in
 	" disabled")	COB_HAS_ISAM="no";;
@@ -176,18 +195,18 @@ export COB_MSG_FORMAT
 	*)		echo "unknown entry for indexed handler: '"$cob_indexed"' please report" && exit 1;;
 	esac
 
-	if test $(grep -i -c "XML library.*disabled" info.out) = 0; then
+	if test $($GREP -i -c "XML library.*disabled" info.out) = 0; then
 		COB_HAS_XML2="yes"
 	else
 		COB_HAS_XML2="no"
 	fi
-	if test $(grep -i -c "JSON library.*disabled" info.out) = 0; then
+	if test $($GREP -i -c "JSON library.*disabled" info.out) = 0; then
 		COB_HAS_JSON="yes"
 	else
 		COB_HAS_JSON="no"
 	fi
 	# see note below
-	if test $(grep -i -c " screen .*disabled" info.out) = 0; then
+	if test $($GREP -i -c " screen .*disabled" info.out) = 0; then
 		COB_HAS_CURSES="yes"
 	else
 		COB_HAS_CURSES="no"
@@ -198,7 +217,7 @@ if test "x$MSYSTEM" != "x" -o "$OSTYPE" = "cygwin"; then
 	# "Redirection is not supported" (at least with PDCurses "wincon" port)
 	# --> disabling the tests for this feature
 	# ncurses is known to work as long as TERM is appropriate
-	if test $(grep -i -c "ncurses" info.out) != 0; then
+	if test $($GREP -i -c "ncurses" info.out) != 0; then
 		if test "x$MSYSTEM" != "x"; then
 			TERM=""
 		else
@@ -209,7 +228,7 @@ if test "x$MSYSTEM" != "x" -o "$OSTYPE" = "cygwin"; then
 	else
 		# manual tests are executed in separate window
 		# and are visible - so no need to handle it there
-		echo "$at_help_all" | grep -q "run_manual_screen" 2>/dev/null
+		echo "$at_help_all" | $GREP -q "run_manual_screen" 2>/dev/null
 		if test $? -ne 0; then
 		   COB_HAS_CURSES="no"
 		fi
