Merge SVN 5605, 5606

diff --git a/tests/atlocal_win b/tests/atlocal_win
--- a/tests/atlocal_win
+++ b/tests/atlocal_win
@@ -24,13 +24,11 @@
 # along with GnuCOBOL.  If not, see <https://www.gnu.org/licenses/>.
 
 
-TEMPLATE="${abs_srcdir}/testsuite.src"
+TEMPLATE="${abs_top_srcdir}/tests/testsuite.src"
 
-COB_SRC_PATH="$(cd ${abs_srcdir}/.. ; pwd)"
+COB_SRC_PATH="${abs_top_srcdir}"
 
-if test "${COB_WIN_BUILDPATH}" = ""; then
-   COB_WIN_BUILDPATH="$COB_SRC_PATH/build_windows/x64/Debug"
-fi
+[ -z "${COB_WIN_BUILDPATH}" ] && COB_WIN_BUILDPATH="$COB_SRC_PATH/build_windows/x64/Debug"
 
 COBC="cobc.exe"
 COBCRUN="cobcrun.exe"
@@ -39,6 +37,14 @@ LOCAL_ENV=""
 
 PATH="${COB_WIN_BUILDPATH}:${PATH}"
 export PATH
+
+if ! command -v "${COBC}" >/dev/null 2>&1; then
+	echo "missing ${COBC} in ${PATH}"
+	return 1
+fi
+
+ABS_COBC="$(which ${COBC})"
+ABS_COBCRUN="$(which ${COBCRUN})"
 
 DIFF=diff
 AWK=awk
@@ -90,19 +96,31 @@ _unset_option () {
 	fi
 }
 
-# possible path conversion for running the testsuite in an environment
-# that doesn't match the one where the tested binaries were built
-# Note: not needed for running the testsuite with MSYS as this translates the path
+# get path without quote and possibly translated (MSYS) for running in an
+# environment that doesn't match the one where the binaries were built
 #       if MSYS_NO_PATHCONV=1 is not set
 _return_path () {
 	if test "$OSTYPE" = "cygwin" -o x$MSYSTEM_CHOST != x; then
 		cygpath -pm "$1"
 	else
 		# check for WSL / Bash on Windows; ignore error messages (file not available)
-		if $($GREP -q "Microsoft" /proc/sys/kernel/osrelease 2>/dev/null); then
-			wslpath -w "$1"
+		if command -v wslpath >/dev/null 2>&1; then
+			IFS=':' read -ra paths <<< "$1"
+			res=""
+			for path in "${paths[@]}"; do
+				# skip empty paths, convert the rest
+				[ -z "$path" ] && continue
+				[ -z "$res" ] || res+=";"
+				res+="$(wslpath -m "$path")"
+			done
+			echo "$res"
 		else
-			echo "$1"
+			# note: we get forward slashes here, and may also quotes,
+			#       which we already add from the outsiode
+			path=$(cmd //c echo "$1")
+			path="${path#\"}"
+			path="${path%\"}"
+			echo "$path"
 		fi
 	fi
 }
@@ -141,13 +159,15 @@ export PATHSEP
 #COB_LIBS="@COB_LIBS@"
 #export COB_CFLAGS COB_LDFLAGS COB_LIBS
 
-COB_CONFIG_DIR="$(_return_path "${abs_top_srcdir}/config")"
-COB_COPY_DIR="$(_return_path "${abs_top_srcdir}/copy")"
-COB_LIBRARY_PATH="$(_return_path "${abs_top_builddir}/extras")${PATHSEP}$(_return_path "${COB_WIN_BUILDPATH}")"
+	COB_CONFIG_DIR="$(_return_path "${abs_top_srcdir}/config")"
+	COB_COPY_DIR="$(_return_path "${abs_top_srcdir}/copy")"
+	COB_LIBRARY_PATH="$(_return_path "${abs_top_builddir}/extras:${COB_WIN_BUILDPATH}")"
 
-export COB_CONFIG_DIR COB_COPY_DIR
-#export LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH LIBPATH
-export COB_LIBRARY_PATH
+	export COB_CFLAGS COB_LIBS
+	export COB_CONFIG_DIR COB_COPY_DIR
+	#export LD_LIBRARY_PATH DYLD_LIBRARY_PATH SHLIB_PATH LIBPATH
+	export COB_LIBRARY_PATH
+
 COB_UNIX_LF=1
 export COB_UNIX_LF
 
@@ -219,7 +239,7 @@ export COB_MSG_FORMAT
 	" C-ISAM")	COB_HAS_ISAM="cisam";;
 	" V-ISAM")	COB_HAS_ISAM="visam";;
 	" EXTFH")	COB_HAS_ISAM="index_extfh";;
-	*)		echo "unknown entry for indexed handler: '"$cob_indexed"' please report" && exit 1;;
+	*)		echo "unknown entry for indexed handler: '"$cob_indexed"' please report" && return 1;;
 	esac
 
 	if test $($GREP -i -c "XML library.*disabled" info.out) = 0; then
