Fix MacOS workflow
* prevent warnings about overlinking by conditionally adding to libs
* prefer configure options for C(PP)FLAGS/LIBS over environment variables
* additional: drop brew-bison as the installed one works

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -43,13 +43,13 @@ jobs:
 
       - name: Install packages
         run: |
-          brew update
-          brew install autoconf automake libtool bison \
-                       help2man texinfo \
-                       berkeley-db@5 json-c libiconv
-          echo "$HOMEBREW_ROOT/bison/bin" >> $GITHUB_PATH
-          echo "LDFLAGS=-L$HOMEBREW_ROOT/berkeley-db@5/lib -L$HOMEBREW_ROOT/libiconv/lib ${LDFLAGS}" >> $GITHUB_ENV
-          echo "CPPFLAGS=-I$HOMEBREW_ROOT/berkeley-db@5/include -I$HOMEBREW_ROOT/libiconv/include ${CPPFLAGS}" >> $GITHUB_ENV
+          brew update || brew update    # seldomly failing in most cases rerun works
+          brew install autoconf automake libtool \
+                       help2man texinfo libiconv \
+                       berkeley-db@5 json-c || (echo "brew install returned $?")
+          # system available bison works fine
+          #brew install bison
+          #echo "$HOMEBREW_ROOT/bison/bin" >> $GITHUB_PATH
 
       - name: Restore VBISAM cache
         if: ${{ matrix.isam == 'vbisam' }}
@@ -101,7 +101,11 @@ jobs:
                        --enable-cobc-internal-checks \
                        --enable-hardening \
                        --with-curses=ncurses \
-                       --prefix=/opt/cobol/gnucobol
+                       --with-json=json-c \
+                       --prefix=/opt/cobol/gnucobol \
+                       --with-iconv --with-libiconv-prefix="$HOMEBREW_ROOT/libiconv" \
+                       BDB_CFLAGS="-I$HOMEBREW_ROOT/berkeley-db@5/include" \
+                       BDB_LIBS="-L$HOMEBREW_ROOT/berkeley-db@5/lib -ldb"                       
 
       - name: Build GnuCOBOL
         run: make -C _build --jobs=$((${NPROC}+1))
